[packages]
rust = ["bob-nvim"]

[packages.archlinux]
regular = [
    "amixer",
    "archcraft-i3wm",
    "archlinux-keyring",
    "autotiling",
    "base-devel",
    "bat",
    "betterbird-bin",
    "betterlockscreen",
    "bob",
    "btop",
    "carla",
    "copyq",
    "dex",
    "diff-so-fancy",
    "eza",
    "fd",
    "feh",
    "fzf",
    "fzy",
    "git",
    "github-cli",
    "gpa-git",
    "helvum",
    "keepassxc",
    "lazygit",
    "lib32-stderred-git",
    "lib32-vulkan-icd-loader",
    "libxnvctrl",
    "lutris",
    "ncdu",
    "neovide",
    "nodejs",
    "nordvpn-bin",
    "npm",
    "pamac-aur",
    "pamixer",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "ptpython",
    "python-pipx",
    "qbittorrent-enchanced",
    "ripgrep",
    "seahorse",
    "sesh-bin",
    "stderred-git",
    "steam-native-runtime",
    "steamtinkerlaunch-git",
    "syncthing",
    "syncthingtray-qt6",
    "tealdeer",
    "telegram-desktop",
    "tmux",
    "todoist-nativefier",
    "vencord",
    "vulkan-icd-loader",
    "wezterm",
    "wine",
    "winecfg",
    "winetricks",
    "wireplumber",
    "zen-browser-avx2-bin",
    "zoxide",
]
nvidia = [
    "lib32-nvidia-utils",
    "lib32-opencl-nvidia",
    "nvidia-dkms",
    "nvidia-settings",
    "nvidia-utils",
    "opencl-nvidia",
]

[packages.darwin]
brews = [
    "asciinema",
    "bash",
    "bat",
    "btop",
    "clang",
    "coreutils",
    "eza",
    "fd",
    "fzf",
    "fzy",
    "gh",
    "git",
    "glow",
    "jq",
    "lazydocker",
    "lazygit",
    "lnav",
    "lua",
    "luajit",
    "luarocks",
    "man-db",
    "ncdu",
    "node",
    "parallel",
    "pipx",
    "ptpython",
    "pyenv",
    "rich",
    "ripgrep",
    "sesh",
    "tealdeer",
    "tmux",
    "tree-sitter",
    "zoxide",
    "zsh",
]
casks = [
    "docker",
    "keepassxc",
    "keycastr",
    "neovide",
    "obsidian",
    "raycast",
    "syncthing",
    "telegram",
    "todoist",
    "wezterm",
    "zen-browser",
]
