#!/usr/bin/env bash

mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
if [[ -d "$1" ]]; then
	eza --oneline --icons --color=always --sort=name --git "$1"
elif [[ "$category" = text ]]; then
	bat --decorations=never --color=always "$1"
else
	exit 1
fi
