#!/bin/bash

# fjq utility
# Dependencies: fzf, jq, bat
# Usage: fjq <json file> [OPTIONAL<query>]
# Example: fjq test.json '.[].name'
# Example: fjq test.json -> you will be prompted to enter the query in fzf

# If your query is incorrect, the whole json file will be previewed as fallback
# And "INVALID QUERY" string will be added to the JSON array
# It is useful when you creating your query in the fzf prompt.
# Otherwise it would be empty preview window

[[ -f /tmp/fjq-last-result ]] && rm /tmp/fjq-last-result
INITIAL_QUERY="${2:-.}"
PREVIEW_COMMAND="bat \
        --color=always \
        --plain \
        --language json \
    <(
        output=\$(jq {q} <$1 2>/dev/null)
        if [[ -n \$output ]] && [[ \$output != 'null' ]]; then
            tee /tmp/fjq_last_result.json <<<\$output
        else
            jq </tmp/fjq_last_result.json 2>/dev/null
        fi
)"
: | fzf \
    --print-query \
    --query "$INITIAL_QUERY" \
    --preview "$PREVIEW_COMMAND" \
    --preview-window 'down,95%,border-rounded'
