"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
linemode = "size_and_mtime"
show_symlink = true
title_format = "{cwd}"

[preview]
tab_size = 4

[open]
append_rules = [
    { mime = "text/*", use = "edit" },

    { name = ".gitignore", use = "edit" },
    { name = ".gitattributes", use = "edit" },
    { name = "pre-commit", use = "edit" },
    { name = "LICENSE", use = "edit" },

    { name = "*Dockerfile", use = "edit" },
    { name = "*Makefile", use = "edit" },
    { name = "*Justfile", use = "edit" },

    { name = "*.txt", use = "edit" },
    { name = "*.log", use = "edit" },
    { name = "*.lock", use = "edit" },

    { name = "*.md", use = "edit" },
    { name = "*.adoc", use = "edit" },
    { name = "*.norg", use = "edit" },

    { name = "*.properties", use = "edit" },
    { name = "*.ini", use = "edit" },
    { name = "*.conf", use = "edit" },
    { name = "*.json", use = "edit" },
    { name = "*.proto", use = "edit" },
    { name = "*.xml", use = "edit" },
    { name = "*.yml", use = "edit" },
    { name = "*.yaml", use = "edit" },
    { name = "*.toml", use = "edit" },

    { name = "*.html", use = "edit" },
    { name = "*.css", use = "edit" },
    { name = "*.js", use = "edit" },
    { name = "*.jsx", use = "edit" },
    { name = "*.ts", use = "edit" },
    { name = "*.tsx", use = "edit" },

    { name = "*.sh", use = "edit" },
    { name = "*.bashrc", use = "edit" },
    { name = "*.fish", use = "edit" },
    { name = "*.zsh", use = "edit" },
    { name = "*.nu", use = "edit" },
    { name = "*.bat", use = "edit" },
    { name = "*.ps1", use = "edit" },

    { name = "*.sql", use = "edit" },
    { name = "*.vim", use = "edit" },
    { name = "*.lua", use = "edit" },

    { name = "*.c", use = "edit" },
    { name = "*.cpp", use = "edit" },
    { name = "*.h", use = "edit" },
    { name = "*.java", use = "edit" },
    { name = "*.jsh", use = "edit" },
    { name = "*.groovy", use = "edit" },
    { name = "*.gradle", use = "edit" },
    { name = "*.kt", use = "edit" },
    { name = "*.dart", use = "edit" },
    { name = "*.rb", use = "edit" },
    { name = "*.cr", use = "edit" },
    { name = "*.nim", use = "edit" },
    { name = "*.nims", use = "edit" },
    { name = "*.nimble", use = "edit" },
    { name = "*.py", use = "edit" },
    { name = "*.jl", use = "edit" },
    { name = "*.go", use = "edit" },
    { name = "*.mod", use = "edit" },
    { name = "*.v", use = "edit" },
    { name = "*.rs", use = "edit" },
    { name = "*.zig", use = "edit" },
    { name = "*.zon", use = "edit" },
    { name = "*.er", use = "edit" },
    { name = "*.ex", use = "edit" },
    { name = "*.exs", use = "edit" },
    { name = "*.gleam", use = "edit" },
    { name = "*.cy", use = "edit" },
    { name = "*.pony", use = "edit" },
]
