[mgr]
show_hidden = true
linemode = "size_and_mtime"
show_symlink = true
title_format = "{cwd}"

[preview]
tab_size = 4

[open]
append_rules = [
    { mime = "text/*", use = "edit" },

    { url = ".gitignore", use = "edit" },
    { url = ".gitattributes", use = "edit" },
    { url = "pre-commit", use = "edit" },
    { url = "LICENSE", use = "edit" },

    { url = "*Dockerfile", use = "edit" },
    { url = "*Makefile", use = "edit" },
    { url = "*Justfile", use = "edit" },

    { url = "*.txt", use = "edit" },
    { url = "*.log", use = "edit" },
    { url = "*.lock", use = "edit" },

    { url = "*.md", use = "edit" },
    { url = "*.adoc", use = "edit" },
    { url = "*.norg", use = "edit" },

    { url = "*.properties", use = "edit" },
    { url = "*.ini", use = "edit" },
    { url = "*.conf", use = "edit" },
    { url = "*.json", use = "edit" },
    { url = "*.proto", use = "edit" },
    { url = "*.xml", use = "edit" },
    { url = "*.yml", use = "edit" },
    { url = "*.yaml", use = "edit" },
    { url = "*.toml", use = "edit" },

    { url = "*.html", use = "edit" },
    { url = "*.css", use = "edit" },
    { url = "*.js", use = "edit" },
    { url = "*.jsx", use = "edit" },
    { url = "*.ts", use = "edit" },
    { url = "*.tsx", use = "edit" },

    { url = "*.sh", use = "edit" },
    { url = "*.bashrc", use = "edit" },
    { url = "*.fish", use = "edit" },
    { url = "*.zsh", use = "edit" },
    { url = "*.nu", use = "edit" },
    { url = "*.bat", use = "edit" },
    { url = "*.ps1", use = "edit" },

    { url = "*.sql", use = "edit" },
    { url = "*.vim", use = "edit" },
    { url = "*.lua", use = "edit" },

    { url = "*.c", use = "edit" },
    { url = "*.cpp", use = "edit" },
    { url = "*.h", use = "edit" },
    { url = "*.java", use = "edit" },
    { url = "*.jsh", use = "edit" },
    { url = "*.groovy", use = "edit" },
    { url = "*.gradle", use = "edit" },
    { url = "*.kt", use = "edit" },
    { url = "*.dart", use = "edit" },
    { url = "*.rb", use = "edit" },
    { url = "*.cr", use = "edit" },
    { url = "*.nim", use = "edit" },
    { url = "*.nims", use = "edit" },
    { url = "*.nimble", use = "edit" },
    { url = "*.py", use = "edit" },
    { url = "*.jl", use = "edit" },
    { url = "*.go", use = "edit" },
    { url = "*.mod", use = "edit" },
    { url = "*.v", use = "edit" },
    { url = "*.rs", use = "edit" },
    { url = "*.zig", use = "edit" },
    { url = "*.zon", use = "edit" },
    { url = "*.er", use = "edit" },
    { url = "*.ex", use = "edit" },
    { url = "*.exs", use = "edit" },
    { url = "*.gleam", use = "edit" },
    { url = "*.cy", use = "edit" },
    { url = "*.pony", use = "edit" },
]
