#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch wezterm with i3 config

# i3 directory

if [ "$1" == "--float" ]; then
	shift
	wezterm start --class='wezterm.float' "${@}"
elif [ "$1" == "--full" ]; then
	shift
	wezterm start --class='wezterm.fullscreen' "${@}"
else
	wezterm start --class='wezterm' "${@}"
fi
