#!/usr/bin/bash

find_xauthority() {
  ps -u "$(id -u)" -o pid= |
    xargs -I{} cat /proc/{}/environ 2>/dev/null |
    tr '\0' '\n' |
    grep -m1 '^XAUTHORITY='
}

until find_xauthority; do
  sleep 0.5
done
