#!/usr/bin/env bash

hyprctl clients -j \
    | jq -r '.[] | select(.tags != null and any(.tags[]; . == "private*")) | .address' \
    | xargs -I{} hyprctl dispatch setprop address:{} noscreenshare toggle
