[buildPlans.Iosevka]
family = "Iosevka"
spacing = "normal" # "term" is fine too
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.Iosevka.variants]
inherits = "ss04"

[buildPlans.Iosevka.variants.design]
zero = "dotted"
punctuation-dot = "round"
tilde = "low"
underscore = "high"
caret = "high"
ascii-grave = "straight"
paren = "normal"
guillemet = "straight"
number-sign = "slanted"
ampersand = "closed"
at = "threefold"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Iosevka.variants.italic]
zero = "dotted"
punctuation-dot = "round"
tilde = "low"
underscore = "high"
caret = "high"
ascii-grave = "straight"
paren = "normal"
guillemet = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Iosevka.variants.oblique]
zero = "dotted"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
underscore = "high"
caret = "high"
ascii-grave = "straight"
paren = "normal"
guillemet = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Iosevka.ligations]
inherits = "dlig"
enables = ["tildeeq", "slasheq", "eqexeq"]

[buildPlans.IosevkaCustom.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IosevkaCustom.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"
