# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
export LOCAL_BIN="$HOME/.local/bin"
export PATH="$LOCAL_BIN:$PATH"
export CONFIG="$HOME/.config"
export XDG_CONFIG_HOME="$HOME/.config"
export NVIM_CONFIG="$CONFIG/nvim"
export ASTRONVIM_CONFIG="$CONFIG/astronvim/lua/user"
export DOTFILES="$HOME/dotfiles"
export ZSH_DOTFILES="$DOTFILES/zsh"
export ZSHRC="$ZSH_DOTFILES/zshrc"
export ZSH="$ZSH_DOTFILES/oh-my-zsh"
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
export EDITOR=nvim
export VISUAL=nvim
export PAGER=bat
export FZF_DEFAULT_OPTS="--bind ctrl-j:down,ctrl-k:up --no-multi --marker ⇒ --pointer  --reverse"
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always {}' --preview-window 'down,50%,border-rounded,+{2}+3/3,~3'"
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH=/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:$HOME/.pyenv/shims:$HOME/Library/pnpm:$HOME/.local/bin:$HOME/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/opt/fzf/bin:$HOME/.cargo/bin:$HOME

export HOMEBREW_AUTO_UPDATING=0
export NVM_LAZY_LOAD=true
# Add colors to Terminal
export LSCOLORS=ExFxBxDxCxegedabagacad
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"
# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
plugins=(
    poetry
    kubectl
    pip
    docker
    gh
    colored-man-pages
    gnu-utils
    copypath
    encode64
    fd
    gpg-agent
    ripgrep
)
[[ ! $(command -v brew) ]] || plugins+=(fzf-brew)
custom_plugins=(
    davidde/git
    jeffreytse/zsh-vi-mode
    zdharma-continuum/fast-syntax-highlighting
    Aloxaf/fzf-tab
)
function zvm_config() {
    ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
    ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
    ZVM_TERM=xterm-256color
}
source "$ZSH_DOTFILES/install_custom_plugins.zsh"
source $ZSH/oh-my-zsh.sh
alias help="nocorrect run-help"
alias v=nvim
alias vim=nvim
[[ ! $(command -v gwhich) ]] || alias which=gwhich
[[ ! $(command -v gawk) ]] || alias awk=gawk
if [[ $(command -v exa) ]]; then
    alias l="exa --long --icons --header --octal-permissions --all --sort date --group-directories-first"
    alias ls="exa --icons --sort name --group-directories-first"
    alias tree="exa --icons --header --sort name --group-directories-first --tree --ignore-glob __pycache__"
    export FZF_ALT_C_OPTS="--preview 'exa --icons --header --sort name --group-directories-first --tree {}'"
fi
if [[ $(command -v python3) ]]; then
    alias p="python"
    alias p3="python3"
fi
if [[ $(command -v keepassxc-cli) ]]; then
    alias kp="keepassxc-cli"
fi
if [[ $(command -v bat) ]]; then
    alias cat="bat"
fi
alias lg=lazygit
alias lzd=lazydocker
alias c=clear
tm() {
    local session_name=${1:-"main"}
    tmux new -A -s $session_name
}
alias xdg-open=open
alias pydoc="python3 -m pydoc"
# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
    fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
    fd --type d --hidden --follow --exclude ".git" . "$1"
}
pyvenv() {
    pyenv virtualenv $1 $2
    pyenv local $2
    pyenv pyright
}
pyenv_init() {
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

}
check_pyenv_init() {
    if [ -f .python-version ]; then
        pyenv_init
    fi
}
# add check_pyenv_init function to precmd_functions array
autoload -U add-zsh-hook
add-zsh-hook precmd check_pyenv_init
luaj() {
    java -cp "$HOME/luaj-jse-3.0.2.jar" lua $1
}
cdl() {
    cd "$(readlink $1)"
}
alias config="cd $CONFIG"
alias av="cd $ASTRONVIM_CONFIG"
alias zshrc="$EDITOR $ZSHRC"
alias asc=asciinema
# User configuratio
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

#Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='nvim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

ulimit -n 10240
unsetopt correct_all
setopt correct
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
export PYENV_ROOT="$HOME/.pyenv"
[[ ! -n $(command -v pyenv) ]] || export PATH="$PYENV_ROOT/bin:$PATH"
[[ ! -f "${HOME}/.iterm2_shell_integration.zsh" ]] || source "${HOME}/.iterm2_shell_integration.zsh"
[[ ! -f "$CONFIG/ptpython/config.py" ]] || export PYTHONSTARTUP="$CONFIG/ptpython/config.py"

function zvm_after_init() {
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}
if [[ $(command -v zoxide) ]]; then
    eval "$(zoxide init zsh)"
    alias cd="z"
    alias cdi="zi"
fi
export GPG_TTY="$TTY"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
if [[ $OSTYPE == "darwin"* ]] && [[ -d "$HOME/.terminfo" ]]; then
    export TERMINFO="$HOME/.terminfo" # this saves your santity on MacOS if you are using TMUX
fi
