[packages.darwin]
brews = [
    "asciinema",
    "bash",
    "bat",
    "bob",
    "btop",
    "coreutils",
    "eza",
    "fd",
    "fzf",
    "fzy",
    "gh",
    "git",
    "glow",
    "jq",
    "lazydocker",
    "llvm",
    "lnav",
    "lua",
    "luajit",
    "luarocks",
    "man-db",
    "ncdu",
    "node",
    "nushell",
    "parallel",
    "pipx",
    "ptpython",
    "pyenv",
    "rich",
    "ripgrep",
    "sesh",
    "tealdeer",
    "tree-sitter",
    "zoxide",
    "zsh",
]
brews_head = [
    "tmux",
    "yazi",
    "lazygit",
]
casks = [
    "docker",
    "keepassxc",
    "keycastr",
    "kitty",
    "neovide",
    "obsidian",
    "raycast",
    "syncthing",
    "telegram",
    "todoist",
    "wezterm@nightly",
    "zen-browser",
]
